version: '3.8'

services:
  db-assets:
    container_name: db-assets
    image: postgres:13
    volumes:
      - pgdata_assets:/var/lib/postgresql/data
    env_file:
      - ./env/db-assets.env
    ports:
      - "5432:5432"
    networks:
      - assets-network

  assets-api:
    container_name: assets-api
    build:
      context: ./assets-api
      dockerfile: docker/Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./assets-api:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./env/assets-api.env
    depends_on:
      - db-assets
    networks:
      - assets-network

  data-extractor:
    container_name: data-extractor
    build:
      context: ./data-extractor
      dockerfile: docker/Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./data-extractor:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./env/data-extractor.env
    depends_on:
      - assets-api
    networks:
      - assets-network

networks:
  assets-network:
    driver: bridge

volumes:
  pgdata_assets:
